# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: w7pool

stages:
- stage: install ,init ,plan
  displayName: install terraform
  
  jobs:
  - job: install
    displayName: install terraform

    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'
      displayName: install terraform
    
    # - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
    #   displayName: 'Terraform backend'
    #   inputs:
    #     backendServiceArm: 'Azure Pass — спонсорское предложение (652d0bc1-0a52-4208-aba4-081164348a87)'
    #     backendAzureRmResourceGroupName: storage
    #     backendAzureRmStorageAccountName: w7tfstate
    #     backendAzureRmContainerName: tfstate
    #     backendAzureRmKey: tf/terraform.tfstate

    - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
      displayName: 'terraform init'
      inputs:
        command: init
        allowTelemetryCollection: false

    
  
#staging
    - task: CmdLine@2
      inputs:
        script: 'terraform workspace select staging || terraform workspace new staging'
      # continueOnError: true
    
    # - task: CmdLine@2
    #   inputs:
    #     script: 'terraform workspace select staging'
    #   continueOnError: true
    - task: CmdLine@2
      inputs:
        script: 'terraform plan -var environment=staging'

      
# production
    - task: CmdLine@2
      inputs:
        script: 'terraform workspace select production || terraform workspace new production'
      # continueOnError: true
    
    # - task: CmdLine@2
    #   inputs:
    #     script: 'terraform workspace select production'
    #   continueOnError: true

    - task: CmdLine@2
      inputs:
        script: 'terraform plan -var environment=production'
        
      
    
  
#publishing
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Pipeline.Workspace)/s'
        ArtifactName: 'drop'
        publishLocation: 'Container'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
